=== Healthedata1/uslab-valuesets/20160324_1405_packageR1.1/lri.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="ValueSetLibrary">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="NoValidation">
					<xs:complexType/>
				</xs:element>
				<xs:element name="ValueSetDefinitions">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="ValueSetDefinition" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="MessageLocation" type="xs:string"/>
										<xs:element name="ValueElement" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute name="CodeSystem" type="xs:string"/>
												<xs:attribute name="CodeSystemVersion" type="xs:string"/>
												<xs:attribute name="DisplayName" use="required" type="xs:string"/>
												<xs:attribute name="Usage" use="required" type="xs:string"/>
												<xs:attribute name="Value" use="required" type="xs:string"/>
												<xs:attribute name="Comments" type="xs:string"/>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="BindingIdentifier" use="required" type="xs:string"/>
									<xs:attribute name="ContentDefinition" use="required" type="xs:string"/>
									<xs:attribute name="Description" use="required" type="xs:string"/>
									<xs:attribute name="Extensibility" use="required" type="xs:string"/>
									<xs:attribute name="Name" use="required" type="xs:string"/>
									<xs:attribute name="Oid" use="required" type="xs:string"/>
									<xs:attribute name="Stability" use="required" type="xs:string"/>
									<xs:attribute name="Version" use="required" type="xs:string"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="Group" use="required" type="xs:string"/>
						<xs:attribute name="Order" use="required" type="xs:byte"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="Description" use="required" type="xs:string"/>
			<xs:attribute name="Name" use="required" type="xs:string"/>
			<xs:attribute name="ValueSetLibraryIdentifier" use="required" type="xs:string"/>
			<xs:attribute name="ValueSetLibraryVersion" use="required" type="xs:decimal"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Healthedata1/uslab-valuesets/20160324_1405_packageR1.1/lri.app-withoids.xml
<?xml version="1.0" encoding="UTF-8"?>
<ValueSetLibrary xsi:noNamespaceSchemaLocation="file:///C:/Users/Eric/Documents/NIST_LOI/Valueset%20stuff/20160324_1405_packageR1.1/lri.xsd" Description="NIST Created" Name="LRI-APP" ValueSetLibraryIdentifier="" ValueSetLibraryVersion="1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<NoValidation/>
	<ValueSetDefinitions Group="HL7" Order="1">
		<ValueSetDefinition BindingIdentifier="HL70155_USL.12" ContentDefinition="Extensional" Description="" Extensibility="Closed" Name="Accept/Application Acknowledgment Conditions" Oid="2.16.840.1.113883.9.195.4.23" Stability="Static" Version="V1.1">
			<ValueElement CodeSystem="HL70155" CodeSystemVersion="2.5.1" Comments="Note that there are constraints on combinations of MSH-15 and MSH-16 in the same message that are described further in each IG." DisplayName="Always" Usage="E" Value="AL"/>
			<ValueElement CodeSystem="HL70155" CodeSystemVersion="2.5.1" DisplayName="Error/reject conditions only" Usage="E" Value="ER"/>
			<ValueElement CodeSystem="HL70155" CodeSystemVersion="2.5.1" DisplayName="Never" Usage="R" Value="NE"/>
			<ValueElement CodeSystem="HL70155" CodeSystemVersion="2.5.1" DisplayName="Successful completion only" Usage="E" Value="SU"/>
		</ValueSetDefinition>
		<ValueSetDefinition BindingIdentifier="HL70155_USL.11" ContentDefinition="Extensional" Description="" Extensibility="Closed" Name="Accept/Application Acknowledgment Conditions" Oid="2.16.840.1.113883.9.195.4.23" Stability="Static" Version="V1.1">
			<ValueElement CodeSystem="HL70155" CodeSystemVersion="2.5.1" Comments="Note that there are constraints on combinations of MSH-15 and MSH-16 in the same message that are described further in each IG." DisplayName="Always" Usage="R" Value="AL"/>
			<ValueElement CodeSystem="HL70155" CodeSystemVersion="2.5.1" DisplayName="Error/reject conditions only" Usage="E" Value="ER"/>
			<ValueElement CodeSystem="HL70155" CodeSystemVersion="2.5.1" DisplayName="Never" Usage="P" Value="NE"/>
			<ValueElement CodeSystem="HL70155" CodeSystemVersion="2.5.1" DisplayName="Successful completion only" Usage="E" Value="SU"/>
		</ValueSetDefinition>
	</ValueSetDefinitions>
</ValueSetLibrary>

=== Healthedata1/uslab-valuesets/20160324_1405_packageR1.1/elr.oru-withoids.xml
<?xml version="1.0" encoding="UTF-8"?>
<ValueSetLibrary xsi:noNamespaceSchemaLocation="file:///C:/Users/Eric/Documents/NIST_LOI/Valueset%20stuff/20160324_1405_packageR1.1/lri.xsd" Description="NIST Created" Name="ELR-ORU" ValueSetLibraryIdentifier="" ValueSetLibraryVersion="1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<NoValidation/>
	<ValueSetDefinitions Group="HL7" Order="1">
		<ValueSetDefinition BindingIdentifier="HL70155_USL.13" ContentDefinition="Extensional" Description="" Extensibility="Closed" Name="Accept/Application Acknowledgment Conditions" Oid="2.16.840.1.113883.9.195.4.23" Stability="Static" Version="V1.1">
			<ValueElement CodeSystem="HL70155" CodeSystemVersion="2.5.1" Comments="Note that there are constraints on combinations of MSH-15 and MSH-16 in the same message that are described further in each IG." DisplayName="Always" Usage="R" Value="AL"/>
			<ValueElement CodeSystem="HL70155" CodeSystemVersion="2.5.1" DisplayName="Error/reject conditions only" Usage="E" Value="ER"/>
			<ValueElement CodeSystem="HL70155" CodeSystemVersion="2.5.1" DisplayName="Never" Usage="P" Value="NE"/>
			<ValueElement CodeSystem="HL70155" CodeSystemVersion="2.5.1" DisplayName="Successful completion only" Usage="E" Value="SU"/>
		</ValueSetDefinition>
		<ValueSetDefinition BindingIdentifier="HL70155_USL.14" ContentDefinition="Extensional" Description="" Extensibility="Closed" Name="Accept/Application Acknowledgment Conditions" Oid="2.16.840.1.113883.9.195.4.23" Stability="Static" Version="V1.1">
			<ValueElement CodeSystem="HL70155" CodeSystemVersion="2.5.1" Comments="Note that there are constraints on combinations of MSH-15 and MSH-16 in the same message that are described further in each IG." DisplayName="Always" Usage="R" Value="AL"/>
			<ValueElement CodeSystem="HL70155" CodeSystemVersion="2.5.1" DisplayName="Error/reject conditions only" Usage="P" Value="ER"/>
			<ValueElement CodeSystem="HL70155" CodeSystemVersion="2.5.1" DisplayName="Never" Usage="E" Value="NE"/>
			<ValueElement CodeSystem="HL70155" CodeSystemVersion="2.5.1" DisplayName="Successful completion only" Usage="E" Value="SU"/>
		</ValueSetDefinition>
		<ValueSetDefinition BindingIdentifier="HL70001_USL.5" ContentDefinition="Extensional" Description="This value set defines all values for the patient administrative sex." Extensibility="Closed" Name="Administrative Sex" Oid="2.16.840.1.113883.9.195.4.1" Stability="Static" Version="V1.1">
			<ValueElement CodeSystem="HL70001" CodeSystemVersion="2.5.1" DisplayName="Ambiguous" Usage="P" Value="A"/>
			<ValueElement CodeSystem="HL70001" CodeSystemVersion="2.5.1" DisplayName="Female" Usage="R" Value="F"/>
			<ValueElement CodeSystem="HL70001" CodeSystemVersion="2.5.1" DisplayName="Male" Usage="R" Value="M"/>
			<ValueElement CodeSystem="HL70001" CodeSystemVersion="2.5.1" DisplayName="Not Applicable" Usage="P" Value="N"/>
			<ValueElement CodeSystem="HL70001" CodeSystemVersion="2.5.1" DisplayName="Other" Usage="P" Value="O"/>
			<ValueElement CodeSystem="HL70001" CodeSystemVersion="2.5.1" DisplayName="Unknown" Usage="R" Value="U"/>
		</ValueSetDefinition>
	</ValueSetDefinitions>
</ValueSetLibrary>
